db.url=jdbc:mysql://localhost:3306/quan_ly_thi_sinh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
db.username=root
db.password=1234

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto=none
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
